with open('templates/versant.html', 'w', encoding='utf-8') as f:
    content = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Versant English Assessment - Charvak</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { font-family: Arial, sans-serif; background: #f8f9fa; }
        .hero { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 40px 0; }
        .section-tab { cursor: pointer; border: 2px solid #e0e0e0; border-radius: 10px; padding: 10px; text-align: center; background: white; }
        .section-tab:hover { border-color: #3ba591; }
        .section-tab.active { border-color: #3ba591; background: #f0faf8; }
        .section-box { background: white; border-radius: 10px; padding: 20px; box-shadow: 0 5px 20px rgba(0,0,0,0.05); margin-top: 20px; }
        .question-item { background: #f8f9fa; border: 1px solid #e0e0e0; border-radius: 8px; padding: 12px; margin-bottom: 8px; }
        .section-content { display: none; }
        .section-content.active { display: block; }
    </style>
</head>
<body>
    <div class="hero text-center">
        <h1>🗣️ Versant English Assessment</h1>
        <p>AI-Generated Unique Questions for Every User | 48 Questions | 50 Minutes</p>
    </div>

    <div class="container py-4">
        <div class="alert alert-info text-center">
            <strong>🤖 AI-Driven:</strong> Every user gets UNIQUE questions generated by AI. No two users see the same questions!
        </div>
    </div>

    <div class="container py-4">
        <div class="row g-2">
            <div class="col-6 col-md-2"><div class="section-tab active" onclick="loadSection('read_aloud')">📖 Read Aloud<br><small>8 Questions</small></div></div>
            <div class="col-6 col-md-2"><div class="section-tab" onclick="loadSection('repeats')">🎧 Repeats<br><small>16 Questions</small></div></div>
            <div class="col-6 col-md-2"><div class="section-tab" onclick="loadSection('sentence_builds')">✏️ Sentence Builds<br><small>10 Questions</small></div></div>
            <div class="col-6 col-md-2"><div class="section-tab" onclick="loadSection('conversations')">💬 Conversations<br><small>10 Questions</small></div></div>
            <div class="col-6 col-md-2"><div class="section-tab" onclick="loadSection('story_retelling')">📝 Story Retelling<br><small>3 Questions</small></div></div>
            <div class="col-6 col-md-2"><div class="section-tab" onclick="loadSection('summary_opinion')">📄 Summary<br><small>1 Question</small></div></div>
        </div>

        <div class="section-box section-content active" id="content-read_aloud">
            <h4>📖 Read Aloud</h4>
            <p class="text-muted">Generating your unique questions...</p>
            <div id="questions-read_aloud"></div>
        </div>
        
        <div class="section-box section-content" id="content-repeats">
            <h4>🎧 Repeats</h4>
            <div id="questions-repeats"></div>
        </div>
        
        <div class="section-box section-content" id="content-sentence_builds">
            <h4>✏️ Sentence Builds</h4>
            <div id="questions-sentence_builds"></div>
        </div>
        
        <div class="section-box section-content" id="content-conversations">
            <h4>💬 Conversations</h4>
            <div id="questions-conversations"></div>
        </div>
        
        <div class="section-box section-content" id="content-story_retelling">
            <h4>📝 Story Retelling</h4>
            <div id="questions-story_retelling"></div>
        </div>
        
        <div class="section-box section-content" id="content-summary_opinion">
            <h4>📄 Summary & Opinion</h4>
            <div id="questions-summary_opinion"></div>
        </div>
    </div>

    <script>
        var sessionId = null;

        async function startSession() {
            const email = prompt('Enter your email to get your unique questions:');
            if (!email) return;
            
            const response = await fetch('/api/versant/start-session', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify({email: email})
            });
            const result = await response.json();
            sessionId = result.session.session_id;
            
            // Load first section
            loadSection('read_aloud');
        }

        async function loadSection(sectionId) {
            // Update tabs
            document.querySelectorAll('.section-tab').forEach(tab => tab.classList.remove('active'));
            event.target.closest('.section-tab').classList.add('active');
            
            // Hide all sections
            document.querySelectorAll('.section-content').forEach(s => s.classList.remove('active'));
            
            // Show selected
            document.getElementById('content-' + sectionId).classList.add('active');
            
            // Load questions
            const questionsDiv = document.getElementById('questions-' + sectionId);
            
            if (questionsDiv.children.length === 0) {
                questionsDiv.innerHTML = '<p class="text-muted">Generating your unique questions...</p>';
                
                if (sessionId) {
                    const response = await fetch('/api/versant/session/' + sessionId + '/' + sectionId);
                    const result = await response.json();
                    
                    if (result.status === 'success') {
                        let html = '';
                        for (let i = 0; i < result.questions.length; i++) {
                            const q = result.questions[i];
                            const text = q.sentence || q.words || q.question || q.topic || q;
                            html += '<div class="question-item"><strong>Question ' + (i + 1) + ':</strong> ' + text + '</div>';
                        }
                        questionsDiv.innerHTML = html;
                    }
                }
            }
        }

        // Start session on page load
        startSession();
    </script>
</body>
</html>'''
    f.write(content)

print('✅ AI-driven Versant page created - unique questions for every user!')
