with open('templates/trainers.html', 'r', encoding='utf-8') as f:
    content = f.read()

# Update course list with duration and market-standard total price
old_courses = '''            <div class="col-md-6"><div class="course-item"><strong>1. Full Stack Web Development</strong> <span class="badge-demand">Very High Demand</span> <span class="badge-course">\</span></div></div>'''

new_courses_with_details = '''            <div class="col-md-6"><div class="course-item"><strong>1. Full Stack Web Development</strong> <span class="badge-demand">Very High Demand</span><br><small>Duration: 12 Weeks | 120 Hours</small><br><span class="badge-course">Total: \,999</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>2. Data Science & Machine Learning</strong> <span class="badge-demand">Very High Demand</span><br><small>Duration: 16 Weeks | 160 Hours</small><br><span class="badge-course">Total: \,999</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>3. Python Programming</strong> <span class="badge-demand">Very High Demand</span><br><small>Duration: 6 Weeks | 60 Hours</small><br><span class="badge-course">Total: \</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>4. AWS Cloud Computing</strong> <span class="badge-demand">Critical Demand</span><br><small>Duration: 10 Weeks | 100 Hours</small><br><span class="badge-course">Total: \,499</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>5. DevOps Engineering</strong> <span class="badge-demand">Very High Demand</span><br><small>Duration: 12 Weeks | 120 Hours</small><br><span class="badge-course">Total: \,999</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>6. Cybersecurity</strong> <span class="badge-demand">Critical Demand</span><br><small>Duration: 14 Weeks | 140 Hours</small><br><span class="badge-course">Total: \,499</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>7. Java Development</strong> <span class="badge-demand">High Demand</span><br><small>Duration: 10 Weeks | 100 Hours</small><br><span class="badge-course">Total: \</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>8. React & Frontend</strong> <span class="badge-demand">High Demand</span><br><small>Duration: 8 Weeks | 80 Hours</small><br><span class="badge-course">Total: \</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>9. SQL & Database</strong> <span class="badge-demand">High Demand</span><br><small>Duration: 4 Weeks | 40 Hours</small><br><span class="badge-course">Total: \</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>10. Docker & Kubernetes</strong> <span class="badge-demand">Very High Demand</span><br><small>Duration: 6 Weeks | 60 Hours</small><br><span class="badge-course">Total: \</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>11. AI & Deep Learning</strong> <span class="badge-demand">Very High Demand</span><br><small>Duration: 16 Weeks | 160 Hours</small><br><span class="badge-course">Total: \,499</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>12. Mobile App Development</strong> <span class="badge-demand">High Demand</span><br><small>Duration: 12 Weeks | 120 Hours</small><br><span class="badge-course">Total: \,499</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>13. Blockchain Development</strong> <span class="badge-demand">High Demand</span><br><small>Duration: 12 Weeks | 120 Hours</small><br><span class="badge-course">Total: \,499</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>14. Data Analytics</strong> <span class="badge-demand">High Demand</span><br><small>Duration: 8 Weeks | 80 Hours</small><br><span class="badge-course">Total: \</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>15. UI/UX Design</strong> <span class="badge-demand">Moderate Demand</span><br><small>Duration: 6 Weeks | 60 Hours</small><br><span class="badge-course">Total: \</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>16. Cloud Architecture</strong> <span class="badge-demand">Critical Demand</span><br><small>Duration: 14 Weeks | 140 Hours</small><br><span class="badge-course">Total: \,999</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>17. Node.js Backend</strong> <span class="badge-demand">High Demand</span><br><small>Duration: 8 Weeks | 80 Hours</small><br><span class="badge-course">Total: \</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>18. Python for Data Science</strong> <span class="badge-demand">Very High Demand</span><br><small>Duration: 10 Weeks | 100 Hours</small><br><span class="badge-course">Total: \,299</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>19. Machine Learning Ops</strong> <span class="badge-demand">High Demand</span><br><small>Duration: 12 Weeks | 120 Hours</small><br><span class="badge-course">Total: \,499</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>20. Spring Boot</strong> <span class="badge-demand">High Demand</span><br><small>Duration: 8 Weeks | 80 Hours</small><br><span class="badge-course">Total: \</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>21. Angular Development</strong> <span class="badge-demand">Moderate Demand</span><br><small>Duration: 6 Weeks | 60 Hours</small><br><span class="badge-course">Total: \</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>22. Ethical Hacking</strong> <span class="badge-demand">Critical Demand</span><br><small>Duration: 12 Weeks | 120 Hours</small><br><span class="badge-course">Total: \,999</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>23. Big Data (Hadoop/Spark)</strong> <span class="badge-demand">High Demand</span><br><small>Duration: 12 Weeks | 120 Hours</small><br><span class="badge-course">Total: \,499</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>24. Software Testing</strong> <span class="badge-demand">Moderate Demand</span><br><small>Duration: 4 Weeks | 40 Hours</small><br><span class="badge-course">Total: \</span> <span class="badge-course">EMI: \/mo</span></div></div>
            <div class="col-md-6"><div class="course-item"><strong>25. Git & DevOps Tools</strong> <span class="badge-demand">High Demand</span><br><small>Duration: 2 Weeks | 20 Hours</small><br><span class="badge-course">Total: \</span> <span class="badge-course">EMI: \/mo</span></div></div>'''

# Remove old course items and add new detailed ones
import re
pattern = r'<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>\s*<div class="col-md-6"><div class="course-item">.*?</div></div>'

content = re.sub(pattern, new_courses_with_details, content, flags=re.DOTALL)

with open('templates/trainers.html', 'w', encoding='utf-8') as f:
    f.write(content)

print('✅ 25 courses with duration and market-standard pricing added!')
