-- ---------------------------------------------------------------------------
-- 2. Seed 25 courses x 3 levels = 75 rows (India price + duration)
-- Multipliers: Beginner 0.60x price / 0.70x weeks; Advanced 1.60x / 1.30x
-- Rounding: <Rs2000 -> nearest 100; >=Rs2000 -> nearest 500; ends in 99
-- REVIEW then apply. ON CONFLICT keeps existing rows safe.
-- ---------------------------------------------------------------------------
INSERT INTO charvak_course_levels (course_name, level, price_inr, duration_weeks, description) VALUES
('Full Stack Web Development','beginner',2999,8,'Beginner track: 8-week curriculum with level-appropriate projects'),
('Full Stack Web Development','intermediate',4999,12,'Intermediate track: 12-week curriculum with level-appropriate projects'),
('Full Stack Web Development','advanced',7999,16,'Advanced track: 16-week curriculum with level-appropriate projects'),
('Data Science & ML','beginner',3499,11,'Beginner track: 11-week curriculum with level-appropriate projects'),
('Data Science & ML','intermediate',5999,16,'Intermediate track: 16-week curriculum with level-appropriate projects'),
('Data Science & ML','advanced',9499,21,'Advanced track: 21-week curriculum with level-appropriate projects'),
('Python Programming','beginner',599,4,'Beginner track: 4-week curriculum with level-appropriate projects'),
('Python Programming','intermediate',999,6,'Intermediate track: 6-week curriculum with level-appropriate projects'),
('Python Programming','advanced',1599,8,'Advanced track: 8-week curriculum with level-appropriate projects'),
('AWS Cloud Computing','beginner',2499,7,'Beginner track: 7-week curriculum with level-appropriate projects'),
('AWS Cloud Computing','intermediate',3999,10,'Intermediate track: 10-week curriculum with level-appropriate projects'),
('AWS Cloud Computing','advanced',6499,13,'Advanced track: 13-week curriculum with level-appropriate projects'),
('DevOps Engineering','beginner',2999,8,'Beginner track: 8-week curriculum with level-appropriate projects'),
('DevOps Engineering','intermediate',4999,12,'Intermediate track: 12-week curriculum with level-appropriate projects'),
('DevOps Engineering','advanced',7999,16,'Advanced track: 16-week curriculum with level-appropriate projects'),
('Cybersecurity','beginner',2999,10,'Beginner track: 10-week curriculum with level-appropriate projects'),
('Cybersecurity','intermediate',4999,14,'Intermediate track: 14-week curriculum with level-appropriate projects'),
('Cybersecurity','advanced',7999,18,'Advanced track: 18-week curriculum with level-appropriate projects'),
('Java Development','beginner',1799,7,'Beginner track: 7-week curriculum with level-appropriate projects'),
('Java Development','intermediate',2999,10,'Intermediate track: 10-week curriculum with level-appropriate projects'),
('Java Development','advanced',4999,13,'Advanced track: 13-week curriculum with level-appropriate projects'),
('React & Frontend','beginner',1499,6,'Beginner track: 6-week curriculum with level-appropriate projects'),
('React & Frontend','intermediate',2499,8,'Intermediate track: 8-week curriculum with level-appropriate projects'),
('React & Frontend','advanced',3999,10,'Advanced track: 10-week curriculum with level-appropriate projects'),
('SQL & Database','beginner',599,3,'Beginner track: 3-week curriculum with level-appropriate projects'),
('SQL & Database','intermediate',999,4,'Intermediate track: 4-week curriculum with level-appropriate projects'),
('SQL & Database','advanced',1599,5,'Advanced track: 5-week curriculum with level-appropriate projects'),
('Docker & Kubernetes','beginner',1499,4,'Beginner track: 4-week curriculum with level-appropriate projects'),
('Docker & Kubernetes','intermediate',2499,6,'Intermediate track: 6-week curriculum with level-appropriate projects'),
('Docker & Kubernetes','advanced',3999,8,'Advanced track: 8-week curriculum with level-appropriate projects'),
('AI & Deep Learning','beginner',3999,11,'Beginner track: 11-week curriculum with level-appropriate projects'),
('AI & Deep Learning','intermediate',6999,16,'Intermediate track: 16-week curriculum with level-appropriate projects'),
('AI & Deep Learning','advanced',10999,21,'Advanced track: 21-week curriculum with level-appropriate projects'),
('Mobile App Development','beginner',2499,8,'Beginner track: 8-week curriculum with level-appropriate projects'),
('Mobile App Development','intermediate',3999,12,'Intermediate track: 12-week curriculum with level-appropriate projects'),
('Mobile App Development','advanced',6499,16,'Advanced track: 16-week curriculum with level-appropriate projects'),
('Blockchain Development','beginner',2999,8,'Beginner track: 8-week curriculum with level-appropriate projects'),
('Blockchain Development','intermediate',4999,12,'Intermediate track: 12-week curriculum with level-appropriate projects'),
('Blockchain Development','advanced',7999,16,'Advanced track: 16-week curriculum with level-appropriate projects'),
('Data Analytics','beginner',1799,6,'Beginner track: 6-week curriculum with level-appropriate projects'),
('Data Analytics','intermediate',2999,8,'Intermediate track: 8-week curriculum with level-appropriate projects'),
('Data Analytics','advanced',4999,10,'Advanced track: 10-week curriculum with level-appropriate projects'),
('UI/UX Design','beginner',1199,4,'Beginner track: 4-week curriculum with level-appropriate projects'),
('UI/UX Design','intermediate',1999,6,'Intermediate track: 6-week curriculum with level-appropriate projects'),
('UI/UX Design','advanced',2999,8,'Advanced track: 8-week curriculum with level-appropriate projects'),
('Cloud Architecture','beginner',3499,10,'Beginner track: 10-week curriculum with level-appropriate projects'),
('Cloud Architecture','intermediate',5999,14,'Intermediate track: 14-week curriculum with level-appropriate projects'),
('Cloud Architecture','advanced',9499,18,'Advanced track: 18-week curriculum with level-appropriate projects'),
('Node.js Backend','beginner',1499,6,'Beginner track: 6-week curriculum with level-appropriate projects'),
('Node.js Backend','intermediate',2499,8,'Intermediate track: 8-week curriculum with level-appropriate projects'),
('Node.js Backend','advanced',3999,10,'Advanced track: 10-week curriculum with level-appropriate projects'),
('Python for Data Science','beginner',2499,7,'Beginner track: 7-week curriculum with level-appropriate projects'),
('Python for Data Science','intermediate',3999,10,'Intermediate track: 10-week curriculum with level-appropriate projects'),
('Python for Data Science','advanced',6499,13,'Advanced track: 13-week curriculum with level-appropriate projects'),
('Machine Learning Ops','beginner',2999,8,'Beginner track: 8-week curriculum with level-appropriate projects'),
('Machine Learning Ops','intermediate',4999,12,'Intermediate track: 12-week curriculum with level-appropriate projects'),
('Machine Learning Ops','advanced',7999,16,'Advanced track: 16-week curriculum with level-appropriate projects'),
('Spring Boot','beginner',1499,6,'Beginner track: 6-week curriculum with level-appropriate projects'),
('Spring Boot','intermediate',2499,8,'Intermediate track: 8-week curriculum with level-appropriate projects'),
('Spring Boot','advanced',3999,10,'Advanced track: 10-week curriculum with level-appropriate projects'),
('Angular Development','beginner',1199,4,'Beginner track: 4-week curriculum with level-appropriate projects'),
('Angular Development','intermediate',1999,6,'Intermediate track: 6-week curriculum with level-appropriate projects'),
('Angular Development','advanced',2999,8,'Advanced track: 8-week curriculum with level-appropriate projects'),
('Ethical Hacking','beginner',3499,8,'Beginner track: 8-week curriculum with level-appropriate projects'),
('Ethical Hacking','intermediate',5999,12,'Intermediate track: 12-week curriculum with level-appropriate projects'),
('Ethical Hacking','advanced',9499,16,'Advanced track: 16-week curriculum with level-appropriate projects'),
('Big Data','beginner',2999,8,'Beginner track: 8-week curriculum with level-appropriate projects'),
('Big Data','intermediate',4999,12,'Intermediate track: 12-week curriculum with level-appropriate projects'),
('Big Data','advanced',7999,16,'Advanced track: 16-week curriculum with level-appropriate projects'),
('Software Testing','beginner',599,3,'Beginner track: 3-week curriculum with level-appropriate projects'),
('Software Testing','intermediate',999,4,'Intermediate track: 4-week curriculum with level-appropriate projects'),
('Software Testing','advanced',1599,5,'Advanced track: 5-week curriculum with level-appropriate projects'),
('Git & DevOps Tools','beginner',299,1,'Beginner track: 1-week curriculum with level-appropriate projects'),
('Git & DevOps Tools','intermediate',499,2,'Intermediate track: 2-week curriculum with level-appropriate projects'),
('Git & DevOps Tools','advanced',799,3,'Advanced track: 3-week curriculum with level-appropriate projects')
ON CONFLICT (course_name, level) DO NOTHING;

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================
